### ISSUE TITLE
Ionic build fails with Cordova 5.x+ (gradle)

### ISSUE THREAD

**Issue by tonymke** [Wizcorp/phonegap-facebook-plugin#1010]
In Cordova 5, build tool was changed from ant to gradle.

Looks like some of the images don't get moved properly in an ionic project because of this. Not sure if the build works building in a native cordova 5.0 project - will test.

**Environment:**
* Windows 8 x64
* Java 8.20 x64
* Cordova 5.0.0
* Ionic 1.4.4
* Android 22 SDK/build tools

**Steps:**
* add android platform `ionic platform add android`
* add plugin `ionic plugin add git@github.com:Wizcorp/phonegap-facebook-plugin.git --variable APP_ID="id" --variable APP_NAME="name" --save`
* attempt to build for android `ionic build android`

**Workaround:**
Roll back to cordova 4.x
```
npm uninstall -g cordova ionic
npm install -g cordova@4.4.0 ionic
```

**Console output**

```
[32mUpdated the hooks directory to have execute permissions[39m
cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-ldpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-mdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-hdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-xhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-xxhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-land-xxxhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-ldpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-mdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-hdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-xhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-xxhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\splash\drawable-port-xxxhdpi-screen.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-ldpi-icon.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-mdpi-icon.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-hdpi-icon.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-xhdpi-icon.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-xxhdpi-icon.png

cp: no such file or directory: C:\Users\Tony\dev\mobile.ionic.riderrewards\resources\android\icon\drawable-xxxhdpi-icon.png

Running command: "C:\Program Files\nodejs\node.exe" C:\Users\Tony\dev\mobile.ionic.riderrewards\hooks\after_prepare\010_add_platform_class.js C:\Users\Tony\dev\mobile.ionic.riderrewards
add to body class: platform-android
Running command: C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\cordova\build.bat 
ANDROID_HOME=C:\Users\Tony\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_20
Running: C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\gradlew cdvBuildDebug -b C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild

:compileDebugNdk UP-TO-DATE

:preDebugBuild

:checkDebugManifest

:CordovaLib:compileLint

:CordovaLib:copyDebugLint UP-TO-DATE

:CordovaLib:mergeDebugProguardFiles UP-TO-DATE

:CordovaLib:preBuild

:CordovaLib:preDebugBuild

:CordovaLib:checkDebugManifest

:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugAidl UP-TO-DATE

:CordovaLib:compileDebugRenderscript UP-TO-DATE

:CordovaLib:generateDebugBuildConfig UP-TO-DATE

:CordovaLib:generateDebugAssets UP-TO-DATE

:CordovaLib:mergeDebugAssets UP-TO-DATE

:CordovaLib:generateDebugResValues UP-TO-DATE

:CordovaLib:generateDebugResources UP-TO-DATE

:CordovaLib:packageDebugResources UP-TO-DATE

:CordovaLib:processDebugManifest UP-TO-DATE

:CordovaLib:processDebugResources UP-TO-DATE

:CordovaLib:generateDebugSources UP-TO-DATE

:CordovaLib:compileDebugJava UP-TO-DATE

:CordovaLib:processDebugJavaRes UP-TO-DATE

:CordovaLib:packageDebugJar UP-TO-DATE

:CordovaLib:compileDebugNdk UP-TO-DATE

:CordovaLib:packageDebugJniLibs UP-TO-DATE

:CordovaLib:packageDebugLocalJar UP-TO-DATE

:CordovaLib:packageDebugRenderscript UP-TO-DATE

:CordovaLib:bundleDebug UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:compileLint

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:copyDebugLint UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:mergeDebugProguardFiles UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:preBuild

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:preDebugBuild

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:checkDebugManifest

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:preDebugTestBuild

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:prepareDebugDependencies

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:compileDebugAidl UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:compileDebugRenderscript UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:generateDebugBuildConfig UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:generateDebugAssets UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:mergeDebugAssets UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:generateDebugResValues UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:generateDebugResources UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:mergeDebugResources UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:processDebugManifest UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:processDebugResources UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:generateDebugSources UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:compileDebugJava UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:processDebugJavaRes UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:packageDebugJar UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:compileDebugNdk UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:packageDebugJniLibs UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:packageDebugLocalJar UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:packageDebugRenderscript UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:packageDebugResources UP-TO-DATE

:com.phonegap.plugins.facebookconnect:riderrewards287606-FacebookLib:bundleDebug UP-TO-DATE

:prepareAndroidComPhonegapPluginsFacebookconnectRiderrewards287606FacebookLibUnspecifiedDebugLibrary UP-TO-DATE

:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE

:prepareDebugDependencies

:compileDebugAidl UP-TO-DATE

:compileDebugRenderscript UP-TO-DATE

:generateDebugBuildConfig UP-TO-DATE

:generateDebugAssets UP-TO-DATE

:mergeDebugAssets UP-TO-DATE

:generateDebugResValues UP-TO-DATE

:generateDebugResources UP-TO-DATE

:mergeDebugResources

Error: Failed to run command:
	C:\Users\Tony\AppData\Local\Android\sdk\build-tools\22.0.1\aapt.exe s -i C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\build\intermediates\exploded-aar\android.com.phonegap.plugins.facebookconnect\riderrewards287606-FacebookLib\unspecified\debug\res\drawable-xxhdpi-v4\com_facebook_button_like_background_selected.png -o C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\build\intermediates\res\debug\drawable-xxhdpi-v4\com_facebook_button_like_background_selected.png
Error Code:
	42
Output:
	C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\build\intermediates\exploded-aar\android.com.phonegap.plugins.facebookconnect\riderrewards287606-FacebookLib\unspecified\debug\res\drawable-xxhdpi-v4\com_facebook_button_like_background_selected.png ERROR: Unable to open PNG file


:mergeDebugResources FAILED



BUILD FAILED



Total time: 2.981 secs

ERROR building one of the platforms: Error: C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\cordova\build.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
```

**Comment by Chuxel** [comment]
This also repros with a basic Cordova CLI project when using Ant in 5.0.0 so it is likely 5.0.0 specific, not Gradle specific.

~~~~~~~~~~~~~~
npm install -g cordova@5.0.0
cordova plugin add com.phonegap.plugins.facebookconnect --variable  APP_ID=123 --variable APP_NAME=nbaer
cordova platform add android
cordova build android
cordova build android -- --ant
~~~~~~~

**Comment by nikhilkh** [comment]
Looks like the path C:\Users\Tony\dev\mobile.ionic.riderrewards\platforms\android\build\intermediates\exploded-aar\android.com.phonegap.plugins.facebookconnect\riderrewards287606-FacebookLib\unspecified\debug\res\drawable-xxhdpi-v4\com_facebook_button_like_background_selected.png

is > 255 characters and hence it's hitting into 'Path too long' error.

**Comment by Chuxel** [comment]
Yeah that was what I hit too though as I dug in there is a problem here if you try to build with Ant and Cordova 5.0.0.  "cordova build android -- --ant".  It expects a ant-build folder to be present and is not.  If you add it by hand everything works, so  this appears to be an Android 4..0.0 platform bug since it works in 4.x.

There may also be some changes in the way that the Android platform handles these things that is exacerbating the problem.  I noticed the plugin ends up using the "id" in config.xml in the path, so if you have a long one it can be a problem.

**Comment by andrewkvavlewhite** [comment]
@Chuxel You sir, deserve a medal.

**Comment by nehil** [comment]
Even I am facing same issue in cordova build. I am using cordova CLI version 5.1.1

Error:

```P-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:45
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\INTEL\android-sdks\build-tools\22.0.0\dx.bat --dex --no-optimiz
e --output C:\MyApps\Impalz\platforms\android\build\intermediates\dex\debug --in
put-list=C:\MyApps\Impalz\platforms\android\build\intermediates\tmp\dex\debug\in
putList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support
/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfo
VersionImpl;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 15.823 secs

C:\MyApps\Impulse\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\MyApps\Impalz\platforms\andro
id\gradlew cdvBuildDebug -b C:\MyApps\Impalz\platforms\android\build.gradle -Dor
g.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\INTEL\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)```

**Comment by Kukiwon** [comment]
I'm having the same issue as @nehil .

**Comment by tonymke** [comment]
The reason for this is actually Windows - if the build process needs to operate on a file with a full path longer than some amount of characters, the build will fail.

I found that by moving my project from my userdir to c:\myproject, builds succeeded.

**Comment by nehil** [comment]
It was never a path issue for me. I just removed android-jar v.4 from platform and it worked perfectly.

**Comment by mabdelfattah** [comment]
@nehil which one of the following jars should I delete:

    $ find ./ -iname 'android-support-v4.jar'                                                                        
    .//platforms/android/build/intermediates/exploded-aar/android.com.phonegap.plugins.facebookconnect/FacebookLib/unspecified/debug/libs/android-support-v4.jar
    .//platforms/android/com.phonegap.plugins.facebookconnect/bkam-FacebookLib/build/intermediates/bundles/debug/libs/android-support-v4.jar
    .//platforms/android/com.phonegap.plugins.facebookconnect/bkam-FacebookLib/build/intermediates/bundles/release/libs/android-support-v4.jar
    .//platforms/android/com.phonegap.plugins.facebookconnect/bkam-FacebookLib/libs/android-support-v4.jar
    .//plugins/com.phonegap.plugins.facebookconnect/platforms/android/FacebookLib/libs/android-support-v4.jar

**Comment by dot-louis** [comment]
@mabdelfattah I tried several fixes for this issue and I could not make any of them work.
So courtesy of https://github.com/Wizcorp/phonegap-facebook-plugin/issues/992#issuecomment-126496533

You may want to switch to a more actively maintained fork that already have taken care of this issue.
- https://github.com/Telerik-Verified-Plugins/Facebook
- https://github.com/Telerik-Verified-Plugins/PushNotification

The procedure to install them is exactly the same.
Cheers

**Comment by nbadiganti** [comment]
I had the same issue with the splash screens for the app. 
Here is my solution, 
Create an image with **2208x2208** resolution and place it in the project resources folder. 
To generate the splash screens, 

```
ionic resources --splash
ionic resources --icon
ionic build android
```

Hope this will help.

**Comment by bent0b0x** [comment]
@nbadiganti running `ionic resources` did solve this issue for me
