### ISSUE TITLE
Build failed when I use Ant

### ISSUE THREAD

**Issue by sgrebnov** [Wizcorp/phonegap-facebook-plugin#1029]
There is the following error when I build the app using `--ant` option (gradle works fine).

```
BUILD FAILED
c:\tools\android-sdk\sdk\tools\ant\build.xml:601: The following error occurred while executing this line:
C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\custom_rules.xml:4: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\ant-build does not exist.
```

Below is full stack trace

```
Running command: c:\temp\testApp\platforms\android\cordova\build.bat --ant
ANDROID_HOME=c:\tools\android-sdk\sdk
JAVA_HOME=c:\Program Files (x86)\Java\jdk1.8.0_11
Executing: ant debug -f c:\temp\testApp\platforms\android\build.xml
Buildfile: c:\temp\testApp\platforms\android\build.xml
Buildfile: c:\temp\testApp\platforms\android\build.xml

-set-mode-check:

-set-debug-files:

-check-env:

-check-env:
 [checkenv] Android SDK Tools Revision 24.2.0
 [checkenv] Installed at c:\tools\android-sdk\sdk

-setup:
 [checkenv] Android SDK Tools Revision 24.2.0
 [checkenv] Installed at c:\tools\android-sdk\sdk

-setup:
     [echo] Project Name: MainActivity
     [echo] Project Name: MainActivity
  [gettype] Project Type: Application  [gettype] Project Type: Application


-set-debug-mode:

-pre-clean:

clean:

-debug-obfuscation-check:

-pre-build:

-build-setup:
   [delete] Deleting directory c:\temp\testApp\platforms\android\bin
   [delete] Deleting directory c:\temp\testApp\platforms\android\gen
[getlibpath] Library dependencies:
[getlibpath] 
[getlibpath] ------------------
[getlibpath] Ordered libraries:
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for MainActivity...

nodeps:

-check-env:
 [checkenv] Android SDK Tools Revision 24.2.0
 [checkenv] Installed at c:\tools\android-sdk\sdk

-setup:
     [echo] Project Name: MainActivity
  [gettype] Project Type: Android Library

-pre-clean:

clean:
   [delete] Deleting directory C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin
[gettarget] Project Target:   Android 5.1.1
[gettarget] API level:        22
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin\res
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin\rsObj
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin\rsLibs
    [mkdir] Created dir: c:\temp\testApp\platforms\android\gen
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin\classes
    [mkdir] Created dir: c:\temp\testApp\platforms\android\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for MainActivity...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.2.0
 [checkenv] Installed at c:\tools\android-sdk\sdk

-setup:
     [echo] Project Name: MainActivity
  [gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
   [delete] Deleting directory C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\gen
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for MainActivity...

nodeps:

-check-env:
 [checkenv] Android SDK Tools Revision 24.2.0
 [checkenv] Installed at c:\tools\android-sdk\sdk

-setup:
     [echo] Project Name: MainActivity
  [gettype] Project Type: Android Library

-pre-clean:

clean:
[gettarget] Project Target:   Android 5.1.1
[gettarget] API level:        22

BUILD SUCCESSFUL
Total time: 1 second
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\res
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\rsObj
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\rsLibs
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\gen
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\classes
    [mkdir] Created dir: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for MainActivity...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 104 source files to C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 3 warnings
    [javac] Creating empty C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\classes\com\facebook\internal\package-info.class
     [echo] Creating library output jar file...
      [jar] Building jar: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\bin\classes.jar

-post-compile:
ERROR building one of the platforms: Error: c:\temp\testApp\platforms\android\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project

BUILD FAILED
c:\tools\android-sdk\sdk\tools\ant\build.xml:601: The following error occurred while executing this line:
C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\custom_rules.xml:4: C:\temp\testApp\platforms\android\com.phonegap.plugins.facebookconnect\hellocordova-FacebookLib\ant-build does not exist.

Total time: 5 seconds

c:\temp\testApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f c:\temp\testApp\platforms\android\build.xml"
Error: c:\temp\testApp\platforms\android\cordova\build.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Sergei\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)


```

**Comment by sgrebnov** [comment]
Sent fix: https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032
