### ISSUE TITLE
Several issues while setting up

### ISSUE THREAD

**Issue by jaylathia** [Wizcorp/phonegap-facebook-plugin#1035]
I gor several errors of the similar kind as the below. Resolved some by replacing android-support-v4.jar with v13.jar....Still no luck.

        UNEXPECTED TOP-LEVEL EXCEPTION:
        java.lang.IllegalArgumentException: already added: Landroid/support/v13/
app/FragmentCompat$ICSFragmentCompatImpl;
                at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection
.java:122)
                at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
                at com.android.dx.command.dexer.Main.processClass(Main.java:732)

                at com.android.dx.command.dexer.Main.processFileBytes(Main.java:
673)
                at com.android.dx.command.dexer.Main.access$300(Main.java:83)
                at com.android.dx.command.dexer.Main$1.processFileBytes(Main.jav
a:602)
                at com.android.dx.cf.direct.ClassPathOpener.processArchive(Class
PathOpener.java:284)
                at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPath
Opener.java:166)
                at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpe
ner.java:144)
                at com.android.dx.command.dexer.Main.processOne(Main.java:632)
                at com.android.dx.command.dexer.Main.processAllFiles(Main.java:5
10)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)
        1 error; aborting

**Comment by kaansoral** [comment]
Use the telerik versions of both fb and push plugins, the issue is solved on them

**Comment by jaylathia** [comment]
I have developed complete app over ionic-ngcordova. Can I use Telerik ?
Please, if you can give me the documentation links to integrate with ngCordova. Thanks.

**Comment by agamemnus** [comment]
Yes, Telerik is just an aggregation site with some curation.

**Comment by kaansoral** [comment]
http://www.telerik.com/company

**Comment by agamemnus** [comment]
@kaansoral: Great. But we're not going to space here, we are trying to get this plugin to work.

**Comment by kaansoral** [comment]
I think you are very confused: https://github.com/Telerik-Verified-Plugins/Facebook

**Comment by agamemnus** [comment]
This is the same plugin.

**Comment by kaansoral** [comment]
These 2 plugins combined solve the dex clash issues, that the op initially experienced

Telerik is a technology company, not an aggregation site

I personally don't use any of their products, yet I appreciate their leadership of cordova plugins, thanks to them and Eddy, these issues are fixed on their forks

**Comment by agamemnus** [comment]
Well, their plugin site is part of the company. But, I got your point, which is why I edited my initial comment above.

**Comment by kaansoral** [comment]
Good :) I think there were misunderstandings on both ends

In any case, if anyone experiences these dex issues, the latest versions of the telerik push+facebook plugins share a modified v4 library that works for both of them

**Comment by agamemnus** [comment]
Hey, P.S.: by any chance do you know how to fix the problem of Cordova appending the project name to directories? (i.e.: for me it's ``$PROJECTNAME-FacebookLib``)

**Comment by kaansoral** [comment]
Nope, never had a problem with that
