### ISSUE TITLE
Cordova android build error: incompatibility with another plugin

### ISSUE THREAD

**Issue by braianj** [Wizcorp/phonegap-facebook-plugin#1043]
After trying and trying, I found that the error that i'm having is an incompatibility between cordova facebook plugin and push plugin. 
If one of those is installed separately, cordova build android works, but if I install both, the error appears:

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:preDexDebug
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/.../Android SDK/adt-bundle-mac-x86_64-20140702/sdk/build-tools/22.0.1/dx --dex --no-optimize --output /.../platforms/android/build/intermediates/dex/debug --input-list=/.../platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

So now I found the problem, but I don't have the answer.

> Cordova 5.0.0
> Android 4.0.0

> Plugins
> com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
> com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
> com.telerik.stripe 1.0.4 "Stripe"
> org.apache.cordova.device 0.3.0 "Device"
> org.apache.cordova.dialogs 0.3.0 "Notification"
> org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
> org.apache.cordova.network-information 0.2.15 "Network Information"
> org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
> org.apache.cordova.vibration 0.3.13 "Vibration"

**Comment by hobbysoldat** [comment]
Well, the problem is that both plugins include the android-support.jar, one in version 4 the other one in version 13 ... they are conflicting. I am currently working on a solution to the problem too!

**Comment by hobbysoldat** [comment]
It seems to be the same error like the jar mismatch in the Troubleshooting guide. https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/TROUBLESHOOTING.md#jar-mismatch-fix-your-dependencies

So the solution would be to delete your android-support-v*.jars in your /lib/ folder. I copied over mine to the  FacebookLib/lib folder of the plugin, because my project seems to require android-support-v13 and it seems backwards compatible.

I automated this with following hook, but there has to be a better solution, maybe using the gradle build system.

    #!/bin/sh
    echo "DELETE ANDROID SUPPORT V4 from FACEBOOK DEPENDENCY - SOLVES      DEPENDENCY CONFLICT WITH GA TRACKING"
    rm -f platforms/android/com.phonegap.plugins.facebookconnect/app2-FacebookLib/libs/android-support-v4.jar
    mv platforms/android/libs/android-support-v13.jar    platforms/android/com.phonegap.plugins.facebookconnect/app2-FacebookLib/libs/android-support-v13.jar

**Comment by braianj** [comment]
I decided to got with my own [fix](https://github.com/phonegap-build/PushPlugin/issues/573#issuecomment-112474982).
Hope it helps

**Comment by anuragranjan242** [comment]
# cordova.system.library.1=com.android.support:support-v4:+
comit file in project.properties 

Enjoy
