### ISSUE TITLE
Conflict with PushPlugin and android-support-v13.jar

### ISSUE THREAD

**Issue by jgirdner** [Wizcorp/phonegap-facebook-plugin#1049]
Not sure if I should file the bug here or on the ```com.phonegap.plugins.PushPlugin``` project.  When I have ```com.phonegap.plugins.facebookconnect ``` and ```com.phonegap.plugins.PushPlugin``` installed together I get the below error. 

It looks like the issue boils down to com.android.support libs.  When you install the push plugin it adds a file to /libs/android-support-v13.jar

and when you install the facebook plugin it adds /com.phonegap.plugins.facebookconnect/FacebookLib/libs/android-support-v4.jar

Not sure what to do to fix this.

Here is some info on my setup.
```
android:minSdkVersion="16" android:targetSdkVersion="22"
```

```
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.10
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.0.0 
OS: Mac OS X Yosemite
Node Version: v0.10.33
Xcode version: Xcode 6.3.2 Build version 6D2105 
```
```
com.ionic.deploy 0.1.6 "IonicDeploy"
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
cordova-plugin-console 1.0.0 "Console"
cordova-plugin-device 1.0.0 "Device"
cordova-plugin-splashscreen 2.0.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
```

```
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/jason/Android/build-tools/22.0.1/dx --dex --no-optimize --output /Users/jason/Sites/mobileapps/ember/platforms/android/build/intermediates/dex/debug --input-list=/Users/jason/Sites/mobileapps/ember/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.147 secs

/Users/jason/Sites/mobileapps/ember/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/jason/Sites/mobileapps/ember/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/jason/Sites/mobileapps/ember/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/jason/Sites/mobileapps/ember/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /Users/jason/Sites/mobileapps/ember/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by augustoabreu** [comment]
See https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1028

**Comment by jgirdner** [comment]
Thank you very much!!!  That fixed my issue.
