### ISSUE TITLE
Problem installing this plugin

### ISSUE THREAD

**Issue by epworthhh** [Wizcorp/phonegap-facebook-plugin#1085]
when i did:

cordova -d plugin add https://github.com/Wizcorp/phonegap-facebook-plugin/ --variable APP_ID="*****" --variable APP_NAME="*****"

have this error:

shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1438943658959/CONTRIBUTING.md'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

**Comment by gmarziou** [comment]
Known issue with cordova-cli 5.1.1, it happens with other plugins, have a look here for workarounds.

https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/9

**Comment by epworthhh** [comment]
Ok, thanks
