### ISSUE TITLE
Login Failure.

### ISSUE THREAD

**Issue by pradeepsekart** [Wizcorp/phonegap-facebook-plugin#1101]
When I try to login through android app. The fb login dialog screen opens and close by resulting in failure. Kindly help me with this.

**Comment by dustinblanchard** [comment]
I'm seeing the same problem. Here's my logcat:

`E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.localeur.release1, PID: 1687
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null object reference
            at org.apache.cordova.facebook.ConnectPlugin$2$1.onCompleted(ConnectPlugin.java:111)
            at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:295)
            at com.facebook.GraphRequest$5.run(GraphRequest.java:1243)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`
