### ISSUE TITLE
Building Android APK breaks

### ISSUE THREAD

**Issue by noldotar** [Wizcorp/phonegap-facebook-plugin#1124]
Comand ```cordova build android --release``` breaks while building
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

:dexRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/Matteo/Library/Android/sdk/build-tools/23.0.1/dx --dex --output /Users/Matteo/Developer/APP/app/platforms/android/build/intermediates/dex/release --input-list=/Users/Matteo/Developer/APP/app/platforms/android/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 39.035 secs

/Users/Matteo/Developer/APP/app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/Matteo/Developer/APP/app/platforms/android/gradlew with args: cdvBuildRelease,-b,/Users/Matteo/Developer/APP/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/Matteo/Developer/APP/app/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/Matteo/Developer/APP/app/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

My Project
Node version: v4.1.0
Cordova version: 5.3.1

Installed platforms: android 4.1.1, ios 3.9.1
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos

Plugins: 
com.paypal.cordova.mobilesdk 3.1.13 "PayPalMobile"
com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
cordova-plugin-actionsheet 2.0.1 "ActionSheet"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
ionic-plugin-keyboard 1.0.7 "Keyboard"
phonegap-plugin-push 1.3.0 "PushPlugin"

**Comment by noldotar** [comment]
iOS IPA has been build correctly

**Comment by nehil** [comment]
Is it building perfectly in debug mode?

**Comment by ZoRDoK** [comment]
Similar problem

**Comment by mattchete** [comment]
Solved by adding a build-extras.gradle file in the platforms/android/ folder, with this content:

configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}

**Comment by ZoRDoK** [comment]
It's because plugin himself include android-support-v4.jar in "libs" filder

**Comment by noldotar** [comment]
I created the build-extras.gradle as @mattchete said and now the error has changed:

```
:compileReleaseJava
/Users/Matteo/Developer/APP/app/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:483: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/Matteo/Developer/APP/app/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileReleaseJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

/Users/Matteo/Developer/APP/app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/Matteo/Developer/APP/app/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/Matteo/Developer/APP/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/Matteo/Developer/APP/app/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/Matteo/Developer/APP/app/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
Push plugin works perfectly without Facebook plugin

**Comment by noldotar** [comment]
I found this https://github.com/phonegap/phonegap-plugin-push/issues/51 and I tried the Hirbod workaround… and it works.
I simply commented the row 483 in platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java
Build successful! YEAH!
