### ISSUE TITLE
build fail on meteor cordova

### ISSUE THREAD

**Issue by maory69** [Wizcorp/phonegap-facebook-plugin#1195]
i'm using meteor cordova, after adding this plugin, i'm trying to "meteor run android-device", but i get this long long next error:

```
App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         

   While running Cordova app for platform Android with options --device:
   Error: Command failed: /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:34:
   error: package android.support.v4.app does not exist
   import android.support.v4.app.NotificationCompat;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:30: error:
   package android.support.v4.app does not exist
   import android.support.v4.app.NotificationCompat;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:65:
   error: package NotificationCompat does not exist
   private final NotificationCompat.Builder builder;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Notification.java:81:
   error: package NotificationCompat does not exist
   NotificationCompat.Builder builder, Class<?> receiver) {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:155: error:
   package NotificationCompat does not exist
   private void applyDeleteReceiver(NotificationCompat.Builder builder) {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:177: error:
   package NotificationCompat does not exist
   private void applyContentReceiver(NotificationCompat.Builder builder) {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:29: error:
   package com.facebook does not exist
   import com.facebook.AppEventsLogger;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:30: error:
   package com.facebook does not exist
   import com.facebook.FacebookDialogException;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:31: error:
   package com.facebook does not exist
   import com.facebook.FacebookException;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:32: error:
   package com.facebook does not exist
   import com.facebook.FacebookOperationCanceledException;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:33: error:
   package com.facebook does not exist
   import com.facebook.Request;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:34: error:
   package com.facebook does not exist
   import com.facebook.Response;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:35: error:
   package com.facebook does not exist
   import com.facebook.Session;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:36: error:
   package com.facebook does not exist
   import com.facebook.SessionState;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:37: error:
   package com.facebook.model does not exist
   import com.facebook.model.GraphObject;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:38: error:
   package com.facebook.model does not exist
   import com.facebook.model.GraphUser;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:39: error:
   package com.facebook.widget does not exist
   import com.facebook.widget.WebDialog;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:40: error:
   package com.facebook.widget.WebDialog does not exist
   import com.facebook.widget.WebDialog.OnCompleteListener;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:56: error: cannot
   find symbol
   private AppEventsLogger logger;
   ^
   symbol:   class AppEventsLogger
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:461: error:
   cannot find symbol
   private void getUserInfo(final Session session) {
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:533: error:
   cannot find symbol
   private void onSessionStateChange(SessionState state, Exception exception) {
   ^
   symbol:   class SessionState
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:592: error:
   cannot find symbol
   private Session session;
   ^
   symbol:   class Session
   location: class ConnectPlugin.WebDialogBuilderRunnable
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:595: error:
   cannot find symbol
   private OnCompleteListener dialogCallback;
   ^
   symbol:   class OnCompleteListener
   location: class ConnectPlugin.WebDialogBuilderRunnable
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:597: error:
   cannot find symbol
   public WebDialogBuilderRunnable(Context context, Session session, String method, Bundle paramBundle, OnCompleteListener dialogCallback)
   {
   ^
   symbol:   class Session
   location: class ConnectPlugin.WebDialogBuilderRunnable
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:597: error:
   cannot find symbol
   public WebDialogBuilderRunnable(Context context, Session session, String method, Bundle paramBundle, OnCompleteListener dialogCallback)
   {
   ^
   symbol:   class OnCompleteListener
   location: class ConnectPlugin.WebDialogBuilderRunnable
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:119: error:
   package NotificationCompat does not exist
   NotificationCompat.BigTextStyle style;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:120: error:
   package NotificationCompat does not exist
   NotificationCompat.Builder builder;
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:122: error:
   package NotificationCompat does not exist
   style = new NotificationCompat.BigTextStyle()
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:125: error:
   package NotificationCompat does not exist
   builder = new NotificationCompat.Builder(context)
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:70: error: cannot
   find symbol
   logger = AppEventsLogger.newLogger(cordova.getActivity());
   ^
   symbol:   variable AppEventsLogger
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:79: error: cannot
   find symbol
   Session session = new Session.Builder(cordova.getActivity()).setApplicationId(applicationId).build();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:79: error:
   package Session does not exist
   Session session = new Session.Builder(cordova.getActivity()).setApplicationId(applicationId).build();
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:80: error: cannot
   find symbol
   if (session.getState() == SessionState.CREATED_TOKEN_LOADED) {
   ^
   symbol:   variable SessionState
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:81: error: cannot
   find symbol
   Session.setActiveSession(session);
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:83: error:
   package Session does not exist
   Session.OpenRequest openRequest = new Session.OpenRequest(cordova.getActivity());
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:83: error:
   package Session does not exist
   Session.OpenRequest openRequest = new Session.OpenRequest(cordova.getActivity());
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:85: error:
   package Session does not exist
   openRequest.setCallback(new Session.StatusCallback() {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:106: error:
   cannot find symbol
   AppEventsLogger.activateApp(cordova.getActivity());
   ^
   symbol:   variable AppEventsLogger
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:113: error:
   cannot find symbol
   Session.getActiveSession().onActivityResult(cordova.getActivity(), requestCode, resultCode, intent);
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:133: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:133: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:169: error:
   package Session does not exist
   Session.NewPermissionsRequest newPermissionsRequest = new Session.NewPermissionsRequest(cordova.getActivity(),
   permissions);
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:169: error:
   package Session does not exist
   Session.NewPermissionsRequest newPermissionsRequest = new Session.NewPermissionsRequest(cordova.getActivity(),
   permissions);
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:185: error:
   package Session does not exist
   session = new Session.Builder(cordova.getActivity()).setApplicationId(applicationId).build();
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:186: error:
   cannot find symbol
   Session.setActiveSession(session);
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:188: error:
   package Session does not exist
   Session.OpenRequest openRequest = new Session.OpenRequest(cordova.getActivity());
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:188: error:
   package Session does not exist
   Session.OpenRequest openRequest = new Session.OpenRequest(cordova.getActivity());
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:192: error:
   package Session does not exist
   openRequest.setCallback(new Session.StatusCallback() {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:205: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:205: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:223: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:223: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:329: error:
   cannot find symbol
   final OnCompleteListener dialogCallback = new OnCompleteListener() {
   ^
   symbol:   class OnCompleteListener
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:329: error:
   cannot find symbol
   final OnCompleteListener dialogCallback = new OnCompleteListener() {
   ^
   symbol:   class OnCompleteListener
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:380: error:
   cannot find symbol
   WebDialog feedDialog = (new WebDialog.FeedDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback).build();
   ^
   symbol: class WebDialog
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:380: error:
   package WebDialog does not exist
   WebDialog feedDialog = (new WebDialog.FeedDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback).build();
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:380: error:
   cannot find symbol
   WebDialog feedDialog = (new WebDialog.FeedDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback).build();
   ^
   symbol: variable Session
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:389: error:
   cannot find symbol
   WebDialog requestsDialog = (new WebDialog.RequestsDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback)
   ^
   symbol: class WebDialog
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:389: error:
   package WebDialog does not exist
   WebDialog requestsDialog = (new WebDialog.RequestsDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback)
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:389: error:
   cannot find symbol
   WebDialog requestsDialog = (new WebDialog.RequestsDialogBuilder(me.cordova.getActivity(), Session.getActiveSession(),
   paramBundle)).setOnCompleteListener(dialogCallback)
   ^
   symbol: variable Session
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:396: error:
   cannot find symbol
   cordova.getActivity().runOnUiThread(new WebDialogBuilderRunnable(me.cordova.getActivity(), Session.getActiveSession(), this.method, paramBundle,
   dialogCallback));
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:416: error:
   cannot find symbol
   final Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:416: error:
   cannot find symbol
   final Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:440: error:
   package Session does not exist
   Session.NewPermissionsRequest newPermissionsRequest = new Session.NewPermissionsRequest(cordova.getActivity(),
   permissionsList);
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:440: error:
   package Session does not exist
   Session.NewPermissionsRequest newPermissionsRequest = new Session.NewPermissionsRequest(cordova.getActivity(),
   permissionsList);
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:463: error:
   package Request does not exist
   Request.newMeRequest(session, new Request.GraphUserCallback() {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:463: error:
   cannot find symbol
   Request.newMeRequest(session, new Request.GraphUserCallback() {
   ^
   symbol:   variable Request
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:481: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:481: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:483: error:
   package Request does not exist
   Request.Callback graphCallback = new Request.Callback() {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:483: error:
   package Request does not exist
   Request.Callback graphCallback = new Request.Callback() {
   ^
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:509: error:
   cannot find symbol
   Request graphRequest = Request.newGraphPathRequest(null, graphAction, graphCallback);
   ^
   symbol:   class Request
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:509: error:
   cannot find symbol
   Request graphRequest = Request.newGraphPathRequest(null, graphAction, graphCallback);
   ^
   symbol:   variable Request
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:534: error:
   cannot find symbol
   final Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:534: error:
   cannot find symbol
   final Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:560: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   class Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:560: error:
   cannot find symbol
   Session session = Session.getActiveSession();
   ^
   symbol:   variable Session
   location: class ConnectPlugin
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:606: error:
   cannot find symbol
   WebDialog shareDialog = (new WebDialog.Builder(context, session, method, paramBundle)).setOnCompleteListener(dialogCallback).build();
   ^
   symbol:   class WebDialog
   location: class ConnectPlugin.WebDialogBuilderRunnable
   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/facebook/ConnectPlugin.java:606: error:
   package WebDialog does not exist
   WebDialog shareDialog = (new WebDialog.Builder(context, session, method,
   paramBundle)).setOnCompleteListener(dialogCallback).build();
   ^
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use unchecked or unsafe operations.
   Note: Recompile with -Xlint:unchecked for details.
   79 errors

   FAILURE: Build failed with an exception.

   * What went wrong:
   Execution failed for task ':compileDebugJava'.
   > Compilation failed; see the compiler error output for details.

   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

   /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command: /home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildDebug,-b,/home/maor/Projects/EveryDamnDay/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```

Tried everything for hours already!! every possible solution i found online, tried installing the package like this: 
meteor add cordova:com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/0e61babb65bc1716b957b6294c7fdef3ce6ace79

or like this :+1: meteor add cordova:com.phonegap.plugins.facebookconnect@0.12.0
or previous versions, but nothing seems to work!

**Comment by jeduan** [comment]
When posting an issue, wrap your logs in triple backticks for better readability (just did)

Not sure what does cordova-meteor does. If it's using gradle, then, it won't be compatible with this plugin, because this uses ant.

**Comment by nikunjchapadia** [comment]
@maory69 have you resolved this issue , i am experiencing same issue.
