### ISSUE TITLE
meteor cordova, build for android not working - multiple dex 

### ISSUE THREAD

**Issue by maory69** [Wizcorp/phonegap-facebook-plugin#1234]
hi, 
i'm using meteor and cordova to develop an android app.
using mac os el capitan, latest meteor (1.2.1).

im having an error while trying to build the app to android, i manage to see that the error is because of the facebook connect plugin that im using.
im using this version of the plugin: com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/c0f8da97a1d65397ada73e958dafed3aeef2e491

and i get this error:

>  Errors executing Cordova commands:         
> 
>    While running Cordova app for platform Android with options --device:
>    Error: Command failed: /Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/cordova/run --device
>    Note: Some input files use or override a deprecated API.
>    Note: Recompile with -Xlint:deprecation for details.
>    Note: Some input files use or override a deprecated API.
>    Note: Recompile with -Xlint:deprecation for details.
>    Note: Some input files use or override a deprecated API.
>    Note: Recompile with -Xlint:deprecation for details.
>    Note: Some input files use or override a deprecated API.
>    Note: Recompile with -Xlint:deprecation for details.
>    Note: Some input files use or override a deprecated API.
>    Note: Recompile with -Xlint:deprecation for details.
>    Note: Some input files use unchecked or unsafe operations.
>    Note: Recompile with -Xlint:unchecked for details.
> 
>    UNEXPECTED TOP-LEVEL EXCEPTION:
>    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
>    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
>    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
>    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
>    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
>    at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
>    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
>    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
>    at com.android.dx.command.dexer.Main.run(Main.java:277)
>    at com.android.dx.command.dexer.Main.main(Main.java:245)
>    at com.android.dx.command.Main.main(Main.java:106)
> 
>    FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':dexDebug'.
>   
>   > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>   > /Users/maor/Library/Android/sdk/build-tools/23.0.2/dx --dex --no-optimize --output /Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/build/intermediates/dex/debug
>   > --input-list=/Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
>   > Error Code:
>   > 2
>   > Output:
>   
>   UNEXPECTED TOP-LEVEL EXCEPTION:
>   com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
>   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
>   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
>   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
>   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
>   at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
>   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
>   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
>   at com.android.dx.command.dexer.Main.run(Main.java:277)
>   at com.android.dx.command.dexer.Main.main(Main.java:245)
>   at com.android.dx.command.Main.main(Main.java:106)
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>   
>   /Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
>   throw e;
>   ^
>   Error code 1 for command: /Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/gradlew with args:
>   cdvBuildDebug,-b,/Users/maor/dev/EDD/everydamnday/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
>   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
>   at ChildProcess.emit (events.js:98:17)
>   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
>   
>   ExitWithCode:

tried everything... all the issues about the conflict with the android-support.v4.jar with other plugins didnt work.
tried to do meteor reset. tried to remove the platform and add it again but nothing worked.
only if i take down the facebook connect plugin it works!

please help me!!!

**Comment by maory69** [comment]
anyone??

**Comment by ruslan-fidesio** [comment]
same problem here :

Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8.1
Node Version: v4.3.0

Is it related to build-tools version ?

**Comment by SandroGrzicic** [comment]
Try deleting the android-support-v4.jar from the platforms/android/FacebookLib/libs/ directory (and/or any other android-support-v4.jar you see in platforms/android).

**Comment by maory69** [comment]
I found a way to fix it, you should add a build-extras.gradle with the next
code:

configurations { all*.exclude group: 'com.android.support', module:
'support-v4' }

**Comment by Purus** [comment]
+1..

Any solution?

**Comment by fernandocoronilla** [comment]
thanks maory69 

+11111111111111

**Comment by adammoisa** [comment]
@maory69 +1 thanks very much. 

Just to make clear to people who might be stuggling:
- Go to the same directory where there is a file build.gradle (/.meteor/local/cordova-build/android)
- Create a new file build-extras.gradle
- Paste:
```
configurations {
    all*.exclude group: 'com.android.support', 
    module: 'support-v4'
}
```

Save and try to run again.
