### ISSUE TITLE
Facebook connect crash Marshmallow

### ISSUE THREAD

**Issue by Xwalk-Company** [Wizcorp/phonegap-facebook-plugin#1294]
Hi,
I have an application in the playstore and when user tries to connect with facebookConnectPlugin.login(["permissions"]);, the app crash with a error log:

`java.lang.RuntimeException: Unable to resume activity {fr.muvzi.timteam/com.facebook.FacebookActivity}: java.lang.IllegalStateException: Activity {fr.muvzi.timteam/com.facebook.FacebookActivity} did not call finish() prior to onResume() completing
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4156)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
    at android.app.ActivityThread.access$1100(ActivityThread.java:222)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalStateException: Activity {fr.muvzi.timteam/com.facebook.FacebookActivity} did not call finish() prior to onResume() completing
    at android.app.Activity.performResume(Activity.java:6999)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
    ... 10 more
`

**Comment by Xwalk-Company** [comment]
Propably the solution [here](http://stackoverflow.com/questions/33185343/facebookactivity-did-not-call-finish-on-api-23)

**Comment by enriqif** [comment]
> Propably the solution here  <

You saved my life!!! :D it work!!..
