### ISSUE TITLE
NO CALL BACK

### ISSUE THREAD

**Issue by Moussawi7** [Wizcorp/phonegap-facebook-plugin#575]
HI,
I already installed the latest version of phonegap-facebook-plugin using CLI.
Everything gonna fine except that I cannot get any response when the user decline the auth process. or in case the app. failed to connect with facebook app.
var plugins_facebook = {
    login: function(callback) {
        facebookConnectPlugin.login(["email", "user_birthday"],
                function(response) {
                    callback(response);
                },
                function(response) {
                    alert("never called");
                    callback(response);
                });
    },
    get_account_information: function(callback) {
        facebookConnectPlugin.api("me/?fields=id,username,gender", ["email", "user_birthday"],
                function(response) {
                    callback(response);
                },
                function(response) {
                          alert("never called");
                    callback(response);
                });
        return;
    }
};
Thanks.

**Comment by infinito84** [comment]
Hi is 2015, and I get the same error, I installed the last version of phonegap-facebook-plugin but the error perssits, look my logcat:
```bash
W/fb4a(:<default>):BlueServiceQueue(15608): Exception during service
W/fb4a(:<default>):BlueServiceQueue(15608): com.facebook.http.protocol.ApiException: [code] 408 [message]: The proxied app is not already installed. [extra]: null
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.protocol.ApiResponseChecker.b(ApiResponseChecker.java:84)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.protocol.ApiResponseChecker.a(ApiResponseChecker.java:163)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.protocol.ApiResponse.i(ApiResponse.java:212)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.platform.auth.server.AuthorizeAppMethod.a(AuthorizeAppMethod.java:275)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.platform.auth.server.AuthorizeAppMethod.a(AuthorizeAppMethod.java:31)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.protocol.ApiResponseHandler.a(ApiResponseHandler.java:56)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.protocol.ApiResponseHandler.handleResponse(ApiResponseHandler.java:29)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:738)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:214)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:167)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:70)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.http.common.FbHttpRequestProcessor$Dispatcher.run(FbHttpRequestProcessor.java:925)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:283)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at com.facebook.common.executors.NamedThreadFactory$1.run(NamedThreadFactory.java:38)
W/fb4a(:<default>):BlueServiceQueue(15608): 	at java.lang.Thread.run(Thread.java:841)
I/ActivityManager( 1015): START u0 {cmp=com.facebook.katana/.ProxyAuth (has extras)} from pid 23105
```

And this a fragment of my code generates that error:

```javascript

        facebookConnectPlugin.login(["public_profile", "email", "user_friends"],
                function(response) {
                     ...
                },
                function(error){
                     ...
                }
        );
```
However, I get response but when I execute the next request I don't get any response (success or error):

```javascript
      facebookConnectPlugin.api("/me?fields=id,first_name,last_name,gender,birthday,email,albums.fields(id,name,type,photos.limit(3).fields(source))",
                ["user_birthday", "user_photos"],
                function(response) {
                     ...
                },
                function(error){
                     ...
                }
        );
```
may you help me? I thank you your support

**Comment by NeXTs** [comment]
I faced a similar problem.
It seems that you are trying to make few requests at same time, it didn't worked for me too.
Try to make second request after first finished. Also for experiment reasons try to put second request in setTimeout.

facebookConnectPlugin.login(["public_profile", "email", "user_friends"],
    function(response) {
        setTimeout(function() {
            facebookConnectPlugin.api("/me?fields=id,first_name,last_name,gender,birthday,email,albums.fields(id,name,type,photos.limit(3).fields(source))", ["user_birthday", "user_photos"],
                function(response) {
                        ...
                },
                function(error) {
                        ...
                }
            );
        }, 500);
    },
    function(error) {
            ...
    }
);

**Comment by infinito84** [comment]
Hi, thank you!, but, i tried your solution and doesn't work for me, however, testing previous version (that only i have the apk :disappointed: ) i got differents results

**Logcat App builded with Phonegap 4.1.2**
```bash
D/CordovaActivity(12613): Incoming Result
D/CordovaActivity(12613): Request code = 64206
D/CordovaActivity(12613): We have a callback to send this result to
D/ConnectPlugin(12613): activity result in plugin: requestCode(64206), resultCode(-1)
D/CordovaActivity(12613): Resuming the App
D/WifiStateMachine( 1015): handleMessage: E msg.what=131155
D/WifiStateMachine( 1015): processMsg: ConnectedState
D/WifiStateMachine( 1015): processMsg: L2ConnectedState
D/WifiStateMachine( 1015): handleMessage: X
I/SFPerfTracer(  290):      triggers: (rate: 1:40) (0 sw vsyncs) (0 skipped) (18:586439 vsyncs) (20:913229)
I/SFPerfTracer(  290):      triggers: (rate: 0:14) (28763 sw vsyncs) (0 skipped) (18:925373 vsyncs) (20:1267360)
I/SFPerfTracer(  290):      triggers: (rate: 1:40) (0 sw vsyncs) (0 skipped) (17:586456 vsyncs) (19:913248)
I/SFPerfTracer(  290):      triggers: (rate: 0:14) (28763 sw vsyncs) (0 skipped) (0:925373 vsyncs) (2:1267362)
D/dalvikvm(12613): GC_CONCURRENT freed 4602K, 43% free 6358K/11096K, paused 6ms+6ms, total 53ms
V/AlarmManager( 1015): sending alarm Alarm{42495718 type 2 com.facebook.katana}
I/ActivityManager( 1015): Process org.kk7.mik.tool (pid 12086) has died.
D/WifiStateMachine( 1015): handleMessage: E msg.what=131155
D/WifiStateMachine( 1015): processMsg: ConnectedState
D/WifiStateMachine( 1015): processMsg: L2ConnectedState
D/WifiStateMachine( 1015): handleMessage: X
```
**App builded with cordova 3.6**
```bash
D/CordovaActivity(10421): Incoming Result
D/CordovaActivity(10421): Request code = 64206
D/CordovaActivity(10421): We have a callback to send this result to
D/ConnectPlugin(10421): activity result in plugin
I/CordovaLog(10421): Changing log level to DEBUG(3)
I/CordovaLog(10421): Found start page location: index.html
D/Whitelist(10421): Unlimited access to network resources
D/CordovaActivity(10421): Resuming the App
D/CordovaActivity(10421): CB-3064: The errorUrl is null
D/WifiStateMachine( 1015): handleMessage: E msg.what=131155
D/WifiStateMachine( 1015): processMsg: ConnectedState
D/WifiStateMachine( 1015): processMsg: L2ConnectedState
D/WifiStateMachine( 1015): handleMessage: X
I/SFPerfTracer(  290):      triggers: (rate: 0:14) (28763 sw vsyncs) (0 skipped) (69:923539 vsyncs) (71:1265131)
I/SFPerfTracer(  290):      triggers: (rate: 1:40) (0 sw vsyncs) (0 skipped) (67:584928 vsyncs) (69:911382)
I/SFPerfTracer(  290):      triggers: (rate: 0:14) (28763 sw vsyncs) (0 skipped) (0:923539 vsyncs) (2:1265135)
I/SFPerfTracer(  290):      triggers: (rate: 785:60832) (compose: 0:295) (post: 0:25) (render: 1:1125) (0:261026 frames) (1:910984)
D/SFPerfTracer(  290):        layers: (4:14) (DimLayer: 0:6)* (FocusedStackFrame: 0:6231)* (StatusBar: 0:41927) (NavigationBar: 0:22408) (DimLayer: 0:10046)* (DimLayer: 0:1196)* (com.android.systemui.ImageWallpaper: 0:4146)* (: 0:102) (com.facebook.katana/com.facebook.katana.ProxyAuthDialog: 0:56)* (com.facebook.katana/com.facebook.katana.ProxyAuthDialog: 0:76)* (com.facebook.katana/com.facebook.katana.ProxyAuthDialog: 0:34)* (org.co.wheels/com.facebook.LoginActivity: 0:24)* (org.co.wheels/org.co.wheels.Wheels: 1:14) 
```
In both versions the error: **com.facebook.http.protocol.ApiException: The proxied app is not already installed.** was present, so i think that the error is in to build the app with phonegap, although in iOS the login works perfect (with phonegap), i have tried all, so, i will try with cordova directly for see what happen

**Comment by infinito84** [comment]
I got to work the app, but the solution that worked for me, was creating a android project, from Eclipse and linking the FacebookLib and CordovaLib projects (taking them from plugin/platforms/android).
