### ISSUE TITLE
Login does not work on Samsung S2

### ISSUE THREAD

**Issue by sebastianzillessen** [Wizcorp/phonegap-facebook-plugin#580]
When I try to login to Facebook via the plugin (latest version on `develop` branch `v.0.6.1`) on a Samsung S2 I get the following error:

```
 Exception during service
 com.facebook.http.protocol.ApiException: The proxied app is not already installed.
    at com.facebook.http.protocol.ApiResponseChecker.b(ApiResponseChecker.java:83)
    at com.facebook.http.protocol.ApiResponseChecker.a(ApiResponseChecker.java:162)
    at com.facebook.http.protocol.ApiResponse.g(ApiResponse.java:239)
    at com.facebook.katana.server.protocol.AuthorizeAppMethod.a(AuthorizeAppMethod.java:272)
    at com.facebook.katana.server.protocol.AuthorizeAppMethod.a(AuthorizeAppMethod.java:29)
    at com.facebook.http.protocol.ApiResponseHandler.a(ApiResponseHandler.java:56)
    at com.facebook.http.protocol.ApiResponseHandler.handleResponse(ApiResponseHandler.java:29)
    at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:280)
    at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:141)
    at com.facebook.http.common.FbHttpRequestProcessor.b(FbHttpRequestProcessor.java:103)
    at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:196)
    at com.facebook.http.protocol.SingleMethodRunnerImpl.a(SingleMethodRunnerImpl.java:374)
    at com.facebook.http.protocol.SingleMethodRunnerImpl.a(SingleMethodRunnerImpl.java:151)
    at com.facebook.http.protocol.AbstractSingleMethodRunner.a(AbstractSingleMethodRunner.java:18)
    at com.facebook.katana.server.handler.PlatformOperationHandler.c(PlatformOperationHandler.java:367)
    at com.facebook.katana.server.handler.PlatformOperationHandler.a(PlatformOperationHandler.java:260)
    at com.facebook.fbservice.service.BlueServiceQueue.e(BlueServiceQueue.java:299)
    at com.facebook.fbservice.service.BlueServiceQueue.d(BlueServiceQueue.java:53)
    at com.facebook.fbservice.service.BlueServiceQueue$3.run(BlueServiceQueue.java:230)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at com.facebook.common.executors.ListenableScheduledFutureImpl.run(ListenableScheduledFutureImpl.java:59)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.os.HandlerThread.run(HandlerThread.java:60)
```

( all lines started with `07-24 16:21:47.914: W/fb4a(:<default>):BlueServiceQueue(12174):` but i removed that for a better overview)

And I get the following Screenshot (after accepting the permissions I asked for).

![screenshot_2014-07-24-16-21-19](https://cloud.githubusercontent.com/assets/300879/3689303/d78acf14-133e-11e4-9cd1-412d94adeb4e.png)

My Javascript code looks like this:

```
facebookConnectPlugin.login(["public_profile", "email", "user_birthday", "user_likes", "user_friends"], success, fail);
```

Any ideas where this could come from?

This does not happen (same application) on a _Nexus 4 (Android 4.4.4)_ **with** installed Facebook App and as well not on a _Samsung S5 (Android 4.4.2)_ **without** Facebook app.

Thanks for your help!

**Comment by infinito84** [comment]
@sebastianzillessen you could indicate me, how can I downgrade the SDK version? and how do I integrate that SDK with phonegap-facebook-plugin? I thank you, your support..

**Comment by sebastianzillessen** [comment]
@infinito84 , well I used my Git history to revert the changes. and used an older version of the repository by defining the version when pulling it.
