### ISSUE TITLE
Build errors: proguard and attributes already defined.

### ISSUE THREAD

**Issue by marie-dk** [Wizcorp/phonegap-facebook-plugin#767]
Cordova 3.6.3-0.2.13
Android SDK: adt-bundle-linux-x86-20140702
Facebook plugin: 0.8
Facebook SDK: 3.16.0

I followed your guidelines but I keep getting these errors when building: 
The line referred to as build.xml line 698, looks like this:

```
proguardFile="${out.absolute.dir}/proguard.txt">
```

The build output with errors...

```
[mergemanifest] Manifest merger disabled. Using project manifest only.
 [echo] Handling aidl files...
 [aidl] No AIDL files to compile.
 [echo] ----------
 [echo] Handling RenderScript files...
 [echo] ----------
 [echo] Handling Resources...
 [aapt] Found new input file
 [aapt] Generating resource IDs...
 [aapt] 
[mergemanifest] Manifest merger disabled. Using project manifest only.
 [echo] Handling aidl files...
 [aidl] No AIDL files to compile.
 [echo] ----------
 [echo] Handling RenderScript files...
 [echo] ----------
 [echo] Handling Resources...
 [aapt] Found new input file
 [aapt] Generating resource IDs...
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:20: error: Attribute "show_pictures" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:21: error: Attribute "extra_fields" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:22: error: Attribute "show_title_bar" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:23: error: Attribute "title_text" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:24: error: Attribute "done_button_text" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:25: error: Attribute "title_bar_background" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:26: error: Attribute "done_button_background" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:29: error: Attribute "multi_select" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:32: error: Attribute "radius_in_meters" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:33: error: Attribute "results_limit" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:34: error: Attribute "search_text" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:35: error: Attribute "show_search_box" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:38: error: Attribute "confirm_logout" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:39: error: Attribute "fetch_user_info" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:40: error: Attribute "login_text" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:41: error: Attribute "logout_text" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:44: error: Attribute "preset_size" has already been defined
 [aapt] /home/jde/Development/tasty/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/res/values/attrs.xml:50: error: Attribute "is_cropped" has already been defined

BUILD FAILED
/home/jde/Development/adt-bundle-linux-x86-20140702/sdk/tools/ant/build.xml:653: The following     error occurred while executing this line:
/home/jde/Development/adt-bundle-linux-x86-20140702/sdk/tools/ant/build.xml:698: null returned: 1

Total time: 6 seconds

/home/jde/Development/tasty/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                        ^
Error code 1 for command: ant with args: debug,-f,/home/jde/Development/tasty/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/jde/Development/tasty/platforms/android/cordova/build: Command failed with exit code 8
at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

I am a web developer and new to building cordova apps. I spend all day trying to fix this... I hope you can provide me with a clue :-)

**Comment by mecampbellsoup** [comment]
@aogilvie @marie-dk any idea why re-building the Cordova project (and adding the plugins fresh, if I understand correctly) solves this problem?

**Comment by mecampbellsoup** [comment]
Hey guys -

In my `platforms/android/project.properties` file, by commenting out the last line as follows:

```xml
# Project target.
target=android-19
android.library.reference.1=CordovaLib
android.library.reference.2=com.phonegap.plugins.facebookconnect/Blade-FacebookLib
#android.library.reference.3=com.phonegap.plugins.facebookconnect/FacebookLib
```
... allowed me to successfully build again on Android, but not sure if this will introduce some bad behavior...
