### ISSUE TITLE
Browser Error " ReferenceError: facebookConnectPlugin is not defined"

### ISSUE THREAD

**Issue by jamesdef** [Wizcorp/phonegap-facebook-plugin#866]
I guess the title says it all.
Anyone having this issue?

Thanks!

**Comment by nasht00** [comment]
Are you supposed to manually copy facebookConnectPlugin.js into your www/js directory or does the plugin does that?

**Comment by nasht00** [comment]
I've copied the file (it's finding it) but I am still have the same error.
Debugging the code:
`
document.getElementById('fb-root').appendChild(e);
            if (!window.FB) {
                // Probably not on server, use the sample sdk
                e.src = 'phonegap/plugin/facebookConnectPlugin/fbsdk.js';
                document.getElementById('fb-root').appendChild(e);
                console.log("Attempt local load: ", e);
            }
`
I see it gets into the "probably not on server" part. I am on a server.

2 things I don't understand:
I see it's dynamically adding the JavaScript SDK on runtime, and it's immediately checking if it was loaded (window.FB). But it doesn't have time to even load the SDK yet. I see in the network panel, it loads AFTER checking that line. So it always go into the if statement.

Secondly, assuming it fails, it's supposed to load "phonegap/plugin..." that directory does not exist for me.

**Comment by aogilvie** [comment]
@jamesdef 

> I have installed it via the cli, I am testing it in the browser platform.

browser platform works like any other platform. you do a CLI install;

```
// add platform
cordova platform add browser

// install plugin
cordova plugin add ../../phonegap-facebook-plugin --variable APP_ID="<asdasd>" --variable APP_NAME="<asdasd>"
```

Now upload your `platforms/browser/www` directory to hosting service or run a local web server.

Update your Facebook developer settings at the developer web portal with something like "website url: localhost" for example (if you are testing locally) and you are good to go.

**Comment by jamesdef** [comment]
this did the trick, thanks!

**Comment by MaicolBen** [comment]
@aogilvie in which field in developer settings add this url?

**Comment by schoettler** [comment]
@jamesdef Hey James i'm having this same error, would you mind showing your solution? The only difference i can tell is that i'm not calling the facebookConnectPlugin.js file manually

**Comment by felquis** [comment]
Hey guys, I know this is not cool, but I want to follow up this thread.

Someone have worked at this issue?

**Comment by gdl276s** [comment]
I ran into "facebookConnectPlugin is not defined" and I followed http://stackoverflow.com/questions/27906239/facebookconnectplugin-is-not-defined-ngcordova-ionic-app which involved importing the file using bower.

I ran into "cordova is not defined" from fbConnectPlugin.js when "serving" the ionic app versus "building" the ionic app.  If you "ionic serve" the app, the cordova.js is not loaded, but if you "ionic build browser" the app, the cordova.js will be put into the build and cordova will now be defined.  I believe that ticket https://github.com/driftyco/ionic-cli/issues/354 will fix this, but currently it is still in "open" status.

Overall, ionic and the phonegap-facebook-plugin need to be improved a little more to support the "browser" platform.

**Comment by matthewgertner** [comment]
@nasht00 (https://github.com/Wizcorp/phonegap-facebook-plugin/issues/866#issuecomment-72333180) is right, the following code from `facebookConnectPlugin.js` is incorrect:

```
    // Bake in the JS SDK
    (function () {
        if (!window.FB) {
            console.log("launching FB SDK");
            var e = document.createElement('script');
            e.src = document.location.protocol + '//connect.facebook.net/en_US/sdk.js';
            e.async = true;
            document.getElementById('fb-root').appendChild(e);
            if (!window.FB) {
                // Probably not on server, use the sample sdk
                e.src = 'phonegap/plugin/facebookConnectPlugin/fbsdk.js';
                document.getElementById('fb-root').appendChild(e);
                console.log("Attempt local load: ", e);
            }
        }
    }());
```

The remote script is loading asynchronously so you can immediately check for `window.FB`. The right way to do this is to attach a `load` listener to the `script` element and do the check there.

Should I submit a pull request?

**Comment by 0x1ad2** [comment]
@matthewgertner if you are able to submit a PR please do.

**Comment by matthewgertner** [comment]
@0x1ad2 So what's the deal with the "local load"? I took a closer look and there doesn't appear to be any `fbsdk.js` in the tree currently? Do we want to just get rid of the fallback or should I download the latest version of the FB SDK and include it in the PR?

**Comment by meeeu** [comment]
include <script src="http://connect.facebook.net/en_US/sdk.js">

get rid of Bake in the JS SDK in facebook-connect-plugin.js

**Comment by muliyul** [comment]
@meeeu including sdk.js didn't work. also what's Bake?

**Comment by meeeu** [comment]
@muliyul include 

/* global FB */
"use strict";

/*
 * @author Ally Ogilvie
 * @copyright Wizcorp Inc. [ Incorporated Wizards ] 2014
 * @file - facebookConnectPlugin.js
 * @about - JavaScript interface for PhoneGap bridge to Facebook Connect SDK
 *
 *
 */

if (!window.cordova) {
// This should override the existing facebookConnectPlugin object created from cordova_plugins.js
    var facebookConnectPlugin = {

        getLoginStatus: function (s, f) {
            // Try will catch errors when SDK has not been init
            try {
                FB.getLoginStatus(function (response) {
                    s(response);
                });
            } catch (error) {
                if (!f) {
                    console.error(error.message);
                } else {
                    f(error.message);
                }
            }
        },

        showDialog: function (options, s, f) {

            if (!options.name) {
                options.name = "";
            }
            if (!options.message) {
                options.message = "";
            }
            if (!options.caption) {
                options.caption = "";
            }
            if (!options.description) {
                options.description = "";
            }
            if (!options.href) {
                options.href = "";
            }
            if (!options.picture) {
                options.picture = "";
            }
            
            // Try will catch errors when SDK has not been init
            try {
                FB.ui(options,
                function (response) {
                    if (response && (response.request || !response.error_code)) {
                        s(response);
                    } else {
                        f(response);
                    }
                });
            } catch (error) {
                if (!f) {
                    console.error(error.message);
                } else {
                    f(error.message);
                }
            }
        },
        // Attach this to a UI element, this requires user interaction.
        login: function (permissions, s, f) {
            // JS SDK takes an object here but the native SDKs use array.
            var permissionObj = {};
            if (permissions && permissions.length > 0) {
                permissionObj.scope = permissions.toString();
            }
            
            FB.login(function (response) {
                if (response.authResponse) {
                    s(response);
                } else {
                    f(response.status);
                }
            }, permissionObj);
        },

        getAccessToken: function (s, f) {
            var response = FB.getAccessToken();
            if (!response) {
                if (!f) {
                    console.error("NO_TOKEN");
                } else {
                    f("NO_TOKEN");
                }
            } else {
                s(response);
            }
        },

        logEvent: function (eventName, params, valueToSum, s, f) {
            // AppEvents are not avaliable in JS.
            s();
        },

        logPurchase: function (value, currency, s, f) {
            // AppEvents are not avaliable in JS.
            s();
        },

        logout: function (s, f) {
            // Try will catch errors when SDK has not been init
            try {
                FB.logout( function (response) {
                    s(response);
                });
            } catch (error) {
                if (!f) {
                    console.error(error.message);
                } else {
                    f(error.message);
                }
            }
        },

        api: function (graphPath, permissions, s, f) {
            // JS API does not take additional permissions
            
            // Try will catch errors when SDK has not been init
            try {
                FB.api(graphPath, function (response) {
                    if (response.error) {
                        f(response);
                    } else {
                        s(response);
                    }
                });
            } catch (error) {
                if (!f) {
                    console.error(error.message);
                } else {
                    f(error.message);
                }
            }
        },

        // Browser wrapper API ONLY
        browserInit: function (appId, version) {
            if (!version) {
                version = "v2.4";
            }
            FB.init({
                appId      : appId,
                status     : true,
                cookie     : true,
                xfbml      : true,
                version    : version
            });
        }
    };
    
    // Bake in the JS SDK


}

it's modified from 
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/browser/www/phonegap/plugin/facebookConnectPlugin/facebookConnectPlugin.js also and

**Comment by meeeu** [comment]
@muliyul you need to include https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/facebookConnectPlugin.js also and can remove code under "Bake in the JS SDK"

also change 

cordova.platformId == "browser" 

to 

!window.cordova

**Comment by 0x1ad2** [comment]
@meeeu I did the steps you suggested but nothing worked.
I also bought the plugin (http://codecanyon.net/item/ionic-phonegapcordova-facebook-native-integration/10228279) to check if they could get it working, unfortunately that's not the case.

I'm currently getting this error on android 
- TypeError: Cannot read property 'getLoginStatus' of undefined
  - at Scope.$scope.registerFacebook (http://192.168.112.45:8100/js/controllers.js:364:34)
  - at fn (eval at <anonymous> (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:21972:15), <anonymous>:4:239)
  - at http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:57514:9
  - at Scope.$eval (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:24673:28)
  - at Scope.$apply (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:24772:23)
  - at HTMLButtonElement.<anonymous> (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:57513:13)
  - at HTMLButtonElement.eventHandler (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:12098:21)
  - at triggerMouseEvent (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:2865:7)
  - at tapClick (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:2854:3)
  - at HTMLDocument.tapTouchEnd (http://192.168.112.45:8100/lib/ionic/js/ionic.bundle.js:2977:5)

**Comment by 0x1ad2** [comment]
Did someone already find a solution to fix this problem?

**Comment by matthewgertner** [comment]
@0x1ad2 I was going to fix this, but we are using PhoneGap Build and I realized the version there is ancient anyway. So instead I use `setTimeout` at startup to wait until `window.FB` is defined, which is obviously a terrible hack. If someone has any idea who is responsible for submitting new versions to PhoneGap Build, I'd be interested to know whether they would be willing to submit a new version. If so I'll fix the issue properly and make a pull request.

**Comment by mebibou** [comment]
@0x1ad2 I managed to make this work in my ionic2 project by:
1. Adding `<div id="fb-root"></div>` and `<script src="http://connect.facebook.net/en_US/sdk.js"></script>` in my `index.html`
2. Adding the following js file into the `index.html` (after `cordova.js` script of course):

```
(function() {
  'use strict';

  if (!window.cordova) {
    window.facebookConnectPlugin = {
      getLoginStatus: function(s, f) {
        // Try will catch errors when SDK has not been init
        try {
          window.FB.getLoginStatus(function(response) {
            s(response);
          });
        }
        catch (error) {
          if (!f) {
            console.error(error.message);
          }
          else {
            f(error.message);
          }
        }
      },

      showDialog: function(options, s, f) {
        if (!options.name) {
          options.name = '';
        }
        if (!options.message) {
          options.message = '';
        }
        if (!options.caption) {
          options.caption = '';
        }
        if (!options.description) {
          options.description = '';
        }
        if (!options.href) {
          options.href = '';
        }
        if (!options.picture) {
          options.picture = '';
        }

        // Try will catch errors when SDK has not been init
        try {
          window.FB.ui(options, function(response) {
            if (response && (response.request || !response.error_code)) {
              s(response);
            }
            else {
              f(response);
            }
          });
        }
        catch (error) {
          if (!f) {
            console.error(error.message);
          }
          else {
            f(error.message);
          }
        }
      },

      // Attach this to a UI element, this requires user interaction.
      login: function(permissions, s, f) {
        // JS SDK takes an object here but the native SDKs use array.
        var permissionObj = {};
        if (permissions && permissions.length > 0) {
          permissionObj.scope = permissions.toString();
        }

        window.FB.login(function(response) {
          if (response.authResponse) {
            s(response);
          }
          else {
            f(response.status);
          }
        }, permissionObj);
      },

      getAccessToken: function(s, f) {
        var response = window.FB.getAccessToken();
        if (!response) {
          if (!f) {
            console.error('NO_TOKEN');
          }
          else {
            f('NO_TOKEN');
          }
        }
        else {
          s(response);
        }
      },

      logEvent: function(eventName, params, valueToSum, s, f) {
        // AppEvents are not avaliable in JS.
        s();
      },

      logPurchase: function(value, currency, s, f) {
        // AppEvents are not avaliable in JS.
        s();
      },

      logout: function(s, f) {
          // Try will catch errors when SDK has not been init
          try {
            window.FB.logout(function(response) {
              s(response);
            });
          }
          catch (error) {
            if (!f) {
              console.error(error.message);
            }
            else {
              f(error.message);
            }
          }
      },

      api: function(graphPath, permissions, s, f) {
        // JS API does not take additional permissions

        // Try will catch errors when SDK has not been init
        try {
          window.FB.api(graphPath, function(response) {
            if (response.error) {
              f(response);
            }
            else {
              s(response);
            }
          });
        }
        catch (error) {
          if (!f) {
            console.error(error.message);
          }
          else {
            f(error.message);
          }
        }
      },

      // Browser wrapper API ONLY
      browserInit: function(appId, version) {
        if (!version) {
          version = 'v2.0';
        }
        window.FB.init({
          appId: appId,
          cookie: true,
          xfbml: true,
          version: version
        });
      }
    };
  }
})();
```

Now you can call `window.facebookConnectPlugin` in your controllers or whatnot to use the sdk the same way you would with the phonegap plugin
