### ISSUE TITLE
install and build fail

### ISSUE THREAD

**Issue by kurtommy** [Wizcorp/phonegap-facebook-plugin#944]
Hi, I'm using ionic and i wont to add a facebookconnect to my project.

I set up succesfully the Android Env a sample app start correctly.

I try to follow this guide:

http://ngcordova.com/docs/plugins/facebook/

but for instance the path of a command poin to 

com.phonegap.plugins.facebookconnect/FacebookLib

insead i found this folder

om.phonegap.plugins.facebookconnect/testing-FacebookLib

if i try to use the correct path i receive a lot of errors.

Any suggestions?

**Comment by vasumahesh1** [comment]
Same Issue ... Any Update on this? I executed these commands:

I changed the target sdks since my target sdk was 22 and I also changed the folder structure (as you had described)

```bash
cordova -d plugin add https://github.com/phonegap/phonegap-facebook-plugin.git --variable APP_ID="123456" --variable APP_NAME="myApp"

android update project --subprojects --path "platforms/android" --target android-22 --library "CordovaLib"

android update project --subprojects --path "platforms/android" --target android-22 --library "com.phonegap.plugins.facebookconnect\myAppxyz-FacebookLib"

cd platforms/android/

ant clean

cd com.phonegap.plugins.facebookconnect\myAppxyz-FacebookLib

ant clean

open -e AndroidManifest.xml

// Updated my target SDK here

ant release

cd ../../../..
```

Now while ant clean it told sdk.dir is missing so I added

to project.properties of "com.phonegap.plugins.facebookconnect\thrillophilia338940-FacebookLib"
```
sdk.dir=C:\\Program Files (x86)\\Android\\android-sdk
```
sdk.dir was already present in my local.properties of platforms/android so I copied it. ant clean was passing after that.


Now after all this it tells me:

>* Where:
Settings file 'P:\3.Cross-Platform\testproject\testproject\platforms\android
\settings.gradle' line: 5

>* What went wrong:
A problem occurred evaluating settings 'android'.
> A path must be specified!

```sh
PS P:\3.Cross-Platform\testproject\testproject> ionic build android
Updated the hooks directory to have execute permissions
Running command: "C:\Program Files\nodejs\node.exe" P:\3.Cross-Platform\testproject\testproject\hooks\after_prepare\010_add_platform_class.js P:\3.Cross-Pla
tform\testproject\testproject
add to body class: platform-android
Running command: "C:\Program Files\nodejs\node.exe" P:\3.Cross-Platform\testproject
testproject\testproject\hooks\after_prepare\020_remove_sass_from_platforms.js P:\3.C
ross-Platform\testproject\testproject
Running command: P:\3.Cross-Platform\testproject\testproject\platforms\andro
id\cordova\build.bat
ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
JAVA_HOME=C:\Program Files\java\jdk1.7.0_79
Running: P:\3.Cross-Platform\testproject\testproject\platforms\android\gradl
ew cdvBuildDebug -b P:\3.Cross-Platform\testproject\testproject\platforms\an
droid\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* Where:
Settings file 'P:\3.Cross-Platform\testproject\testproject\platforms\android
\settings.gradle' line: 5

* What went wrong:
A problem occurred evaluating settings 'android'.
> A path must be specified!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 0.668 secs

P:\3.Cross-Platform\testproject\testproject\platforms\android\cordova\node_m
odules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "P:\3.Cross-Platform\testproject\testproject\platforms\android\gradlew cdvBuildDebug -b P:\3.Cross-Platform\testproject\testproject\platforms\android\build.gradle -Dorg.gradle.daemon=tr
ue"
ERROR building one of the platforms: Error: P:\3.Cross-Platform\testproject\testproject\platforms\android\cordova\build.bat: Command failed with exit code 8

You may not have the required environment or OS to build this project
Error: P:\3.Cross-Platform\testproject\testproject\platforms\android\cordova
\build.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Vasu\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)
PS P:\3.Cross-Platform\testproject\testproject> cordova build android
Running command: "C:\Program Files\nodejs\node.exe" P:\3.Cross-Platform\testproject
testproject\testproject\hooks\after_prepare\010_add_platform_class.js P:\3.Cross-Pla
tform\testproject\testproject
add to body class: platform-android
Running command: "C:\Program Files\nodejs\node.exe" P:\3.Cross-Platform\testproject
testproject\testproject\hooks\after_prepare\020_remove_sass_from_platforms.js P:\3.C
ross-Platform\testproject\testproject
Running command: P:\3.Cross-Platform\testproject\testproject\platforms\andro
id\cordova\build.bat
ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
JAVA_HOME=C:\Program Files\java\jdk1.7.0_79
Running: P:\3.Cross-Platform\testproject\testproject\platforms\android\gradl
ew cdvBuildDebug -b P:\3.Cross-Platform\testproject\testproject\platforms\an
droid\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* Where:
Settings file 'P:\3.Cross-Platform\testproject\testproject\platforms\android
\settings.gradle' line: 5

* What went wrong:
A problem occurred evaluating settings 'android'.
> A path must be specified!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 0.715 secs
```
