### ISSUE TITLE
Error Plugin Facebook Cordova = Command Exit 8

### ISSUE THREAD

**Issue by over12** [Wizcorp/phonegap-facebook-plugin#960]
i am with that problem for compiling my aplication using cordova cli... that is error:

/Users/roni/Dropbox/Arquivos/Phonegap/guardanapo/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/Users/roni/Dropbox/Arquivos/Phonegap/guardanapo/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /Users/roni/Dropbox/Arquivos/Phonegap/guardanapo/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

Already follow the steps in this link: Cordova 3.4 Facebook connect, add Library This too: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/436

But not working... changed in all facebook library files the target for api android-19 manually.

**Comment by MaicolBen** [comment]
+1
