### ISSUE TITLE
using websql for storage thows errors

### ISSUE THREAD

**Issue by gasperz** [Wizcorp/phonegap-facebook-plugin#984]
Hi,
I am using sencha touch (2.4) with cordova build on Android simulator. So no facebook app is installed. I would like to store accessToken in websql storage (on success callback). but i receive console error:
success from console:  
```javascript
Object {authResponse: Object, status: "connected"}
authResponse: Object
accessToken: "CAAKhWeZAhEOwBAHaVOVbkWqgIRRprL5M34dDKIrROU1fKqhav1mfVlysk6ZBDkcbZC9vF6ObZCja5yAUs82F2ciWIflUY9t27FhBx2S6mSUOrDIaeZA3ZBLZBZB3CIIeHKZBdsKB17a1jZAP8QY3CaTMslYx3oW39RZBFPWmZC7JyoVucyEinduyZCngPdlVjnfIm2haOwGBvqkWuL8EXIAIWn7zI"
expiresIn: "5146805"
session_key: true
sig: "..."
userID: "291809714353608"
__proto__: Object
status: "connected"
__proto__: Object
 app.js:1
Error in Success callbackId: FacebookConnectPlugin578981346 : SecurityError: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context. cordova.js:305
processMessage failed: Error: SecurityError: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context. cordova.js:1075
processMessage failed: Stack: Error: Failed to execute 'openDatabase' on 'Window': Access to the WebDatabase API is denied in this context.
    at Ext.cmd.derive.getDatabaseObject (file:///android_asset/www/app.js:1:423684)
    at Ext.cmd.derive.create (file:///android_asset/www/app.js:1:416859)
    at Ext.cmd.derive.runOperation (file:///android_asset/www/app.js:1:359772)
    at Ext.cmd.derive.runNextOperation (file:///android_asset/www/app.js:1:359270)
    at Ext.cmd.derive.start (file:///android_asset/www/app.js:1:359217)
    at Ext.cmd.derive.batch (file:///android_asset/www/app.js:1:361718)
    at Ext.cmd.derive.sync (file:///android_asset/www/app.js:1:411384)
    at c (file:///android_asset/www/app.js:1:502078)
    at file:///android_asset/www/app.js:1:501784
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:286:58) cordova.js:1076
processMessage failed: Message: S01 FacebookConnectPlugin578981346 {"authResponse":{"userID":"291809714353608","accessToken":"CAAKhWeZAhEOwBAHaVOVbkWqgIRRprL5M34dDKIrROU1fKqhav1mfVlysk6ZBDkcbZC9vF6ObZCja5yAUs82F2ciWIflUY9t27FhBx2S6mSUOrDIaeZA3ZBLZBZB3CIIeHKZBdsKB17a1jZAP8QY3CaTMslYx3oW39RZBFPWmZC7JyoVucyEinduyZCngPdlVjnfIm2haOwGBvqkWuL8EXIAIWn7zI","session_key":true,"expiresIn":"5146805","sig":"..."},"status":"connected"} 
```

I am using this code:
```javascript
facebookConnectPlugin.login(["email"], function(success){
    console.log('success from console: ', success);
    if (success.status === 'connected') {
        saveSetting(success.authResponse.accessToken);
//         alert('successfuly logged');
        Ext.Msg.alert('Facebook', 'You are logged in.', Ext.emptyFn);
    }
}, function(failure) {
    console.log('Failed from console:', failure);
//     alert('failure with logging');
    Ext.Msg.alert('Facebook', "Sign in to facebook failed: " + JSON.stringify(failure));
});


function saveSetting(token) {
    var store = Ext.StoreManager.lookup('SFacebook');
    store.add({token: token});
    store.sync();
}
```

What is also strange to me is that "console.log('success from console: ', success);" is executed immediately and not after I enter login credentials. Why is that?

I forgot to mention. This same app works on iOs simulator and devices.

**Comment by aogilvie** [comment]
Hi, I don't know what your `saveSetting` function is doing, I am not familiar with Sencha. However, if you are getting status connected and a valid accesstoken in the success callback then I can see no problem with the plugin. I cannot help you with Sencha because I have never used it, I suggest checking with the Sencha forums and saving a string with `saveSetting` outside of the facebook plugin methods.
