### ISSUE TITLE
User Cancelled Dialog Lolipop on Login

### ISSUE THREAD

**Issue by snakepit13** [Wizcorp/phonegap-facebook-plugin#985]
Hi, i follow the instruction for install the plugin, i generate the Hash for Android and in 4.1.2 and 4.4.4 can login fine, but in Lolipop im getting a "User cancelled dialog" error (4201), using the logcat i watch this error :

I/ActivityManager(  595): Displayed com.facebook.katana/.ProxyAuthDialog: +193ms (total +231ms)
W/fb4a(:<default>):BlueServiceQueue(10875): Exception during service
W/fb4a(:<default>):BlueServiceQueue(10875): com.facebook.proxygen.HttpNetworkException: connect failed: errno = 101: Network is unreachable
W/fb4a(:<default>):BlueServiceQueue(10875):     at com.facebook.proxygen.LigerHttpResponseHandler.handleError(LigerHttpResponseHandler.java:228)
W/fb4a(:<default>):BlueServiceQueue(10875):     at com.facebook.proxygen.LigerHttpResponseHandler.onError(LigerHttpResponseHandler.java:209)
W/fb4a(:<default>):BlueServiceQueue(10875):     at com.facebook.proxygen.JniHandler.onError(JniHandler.java:91)
W/fb4a(:<default>):BlueServiceQueue(10875):     at com.facebook.proxygen.EventBase.loopForever(Native Method)
W/fb4a(:<default>):BlueServiceQueue(10875):     at com.facebook.proxygen.HTTPThread.run(HTTPThread.java:32)
W/fb4a(:<default>):BlueServiceQueue(10875):     at java.lang.Thread.run(Thread.java:818)
E/fb4a(:<default>):PlatformDialogActivity(10875): Login failed due to error: CONNECTION_FAILURE: CONNECTION_FAILURE

I suppose that i got a connection permission problem or something like that, but i check my config.xml and i have this :

"<access origin="*"/>"

At now, im using phonegap build becuase i have not mac to build in iOS and only have plugin version 0.9.0 instead of 0.11.0, but if i build with 0.11.0 locally (only for android) i have the same problem

**Comment by blckshrk** [comment]
Hi,

I got the same problem on both 4.1 and 5.0.2.

I test it with `develop`, `master`and `v0.11.0` branches. Nothing changes. The strange fact is that the error appeared magically...

**Comment by snakepit13** [comment]
Yes, my workarround about this is change my wifi, i dont know why i have to do that and why in other wifi works but changing to my nighboord wifi i can connect wihtout a problems

**Comment by omefire** [comment]
I'm facing the same issue. Any solution to this ?

**Comment by ismailsaglam** [comment]
I'm getting the same error. Yesterday was working with no error. Is there any solution?
Or is there anyone who know the reason?

**Comment by Freundschaft** [comment]
by the way, I found the real issue behind this for me:
calling login works only the first time, after that, subsequent calls to facebook login would result in 4201 user cancelled dialog.
in your code, check first if the user is already logged in with getLoginStatus and only if that fails, run login
