### ISSUE TITLE
Errors on both Android and iOS

### ISSUE THREAD

**Issue by kramer65** [Wizcorp/phonegap-facebook-plugin#989]
I'm trying to use this plugin on both iOS and Android, but on both I get an error (see below). Any idea what could be wrong? All tips are welcome!

For Android I get:

```
file:///android_asset/www/lib/phonegap-facebook-plugin-master/facebookConnectPlugin.js: Line 181 : Uncaught ReferenceError: require is not defined
file:///android_asset/www/js/app.js: Line 23 : Uncaught TypeError: Cannot read property 'Keyboard' of undefined
file:///android_asset/www/lib/ionic/js/ionic.bundle.js: Line 19387 : TypeError: Cannot call method 'login' of undefined
    at Scope.$scope.fbLogin (file:///android_asset/www/js/controllers.js:10:31)
    at $parseFunctionCall (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20124:18)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:50863:9
    at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22178:28)
    at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22276:23)
    at HTMLButtonElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:50862:13)
    at HTMLButtonElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10823:21)
    at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2811:7)
    at tapClick (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2800:3)
    at HTMLDocument.tapTouchEnd (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2918:5)
```

and on iOS I get:

```
[Error] Error: undefined is not an object (evaluating 'facebookConnectPlugin.login')
fbLogin@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB22B6DC5AA9/TC.app/www/js/controllers.js:10:30
$parseFunctionCall@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F2-BB06-EB24B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:20124:23
file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB24B6DC5AB9/TC.app/www/lib/ionic/js/ionic.bundle.js:50863:21
$eval@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB24B2DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:22178:28
$apply@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB22B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:22276:28
file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB24B6DC5AA2/TC.app/www/lib/ionic/js/ionic.bundle.js:50862:19
eventHandler@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB02-EB24B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:10823:25
dispatchEvent@[native code]
triggerMouseEvent@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-42F4-BB06-EB24B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:2811:20
tapClick@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB14B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:2800:20
tapTouchEnd@file:///private/var/mobile/Containers/Bundle/Application/464EF236-E09F-41F4-BB06-EB14B6DC5AA9/TC.app/www/lib/ionic/js/ionic.bundle.js:2918:13
	(anonymous function) (ionic.bundle.js, line 19387)
	(anonymous function) (ionic.bundle.js, line 16350)
	$apply (ionic.bundle.js, line 22278)
	(anonymous function) (ionic.bundle.js, line 50862)
	eventHandler (ionic.bundle.js, line 10823)
	dispatchEvent ([native code], line 0)
	triggerMouseEvent (ionic.bundle.js, line 2811)
	tapClick (ionic.bundle.js, line 2800)
	tapTouchEnd (ionic.bundle.js, line 2918)
```

**Comment by robotvert** [comment]
I'm no cordova plugin developer but along the road using this plugin I'd get errors around cordova, require and module not being defined so [in my fork](https://github.com/robotvert/phonegap-facebook-plugin) I twealed the js file a bit to workaround these.

Not sure this is The Right Way™ so use at your own risk.

@aogilvie any idea why these throw errors in the first place? updating cordova to 5.0.0 seems to have triggered the error mentioned here but `module.exports` has never been working for me.
