### ISSUE TITLE
Facebookconnect blugin

### ISSUE THREAD

**Issue by VapiSoft** [Wizcorp/phonegap-facebook-plugin#993]
I worked with: com.phonegap.plugins.facebookconnect for more than a year and it worked OK.
About two months ago, I started getting errors in the build that something is wrong with the virsion (so it didn't finsh the PhoneGap Build).
So Amir told me to use one of the following plugins:
	<gap:plugin name="nickreed.com.phonegap.plugins.facebookconnect">
	<gap:plugin name="jfaris.com.phonegap.plugins.facebookconnect">
but for both of them I get: an error in the PhoneapBuild: 
              plugin unsupported: jfaris.com.phonegap.plugins.facebookconnect

I am lost, what can I do?

**Comment by jfaris** [comment]
My guess is you need to add source="plugins.cordova.io" to the plugin definition in your config.xml

**Comment by VapiSoft** [comment]
What do you mean? where do i pit it? how (what is the full line)?

**Comment by jfaris** [comment]
````xml
<gap:plugin name="jfaris.com.phonegap.plugins.facebookconnect" version="0.11.0-jfaris.0" source="plugins.cordova.io">
        <param name="APP_ID" value="{your app id}"/>
        <param name="APP_NAME" value="{your app name}"/>
</gap:plugin>
````

**Comment by VapiSoft** [comment]
Now I get an error in The PhonegapBuild: 
and the Log is:

Build Date: 2015-04-28 21:00:17 +0000
----------------------------------------------
debug: Creating Cordova project for the Android platform:
	Path: ../../../../../../project
	Package: com.mobile_gap.trips
	Name: Trips
	Android target: android-21
Copying template files...
Running: android update project --subprojects --path "../../../../../../project" --target android-21 --library "CordovaLib"
/bin/sh: android: command not found


/home/ec2-user/gimlet/var/android/3.7.0/bin/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Command failed: /bin/sh: android: command not found

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
